---
- name: Add the OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- ansible.builtin.include_tasks: "tomcat-setup-{{ ansible_os_family }}.yml"
